### PR TITLE
Don't parse response on code 204

### PR DESCRIPTION
**Pull request by SLonoed**
When server return code 204(No Content) lib must not parse content
because it throw error

More info about 204
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5

### CODE REVIEW

**Comment by Mitranim** [comment]
Thanks for the request. There doesn't seem to be any need for that, as the browser automatically discards the response body. I checked in Chrome, FF and Safari, sending some data with a 204 code from a local server; all browsers discarded the response body, and xhttp interceptors received an empty string as the data argument.

I think we should keep the parsing behaviour as-is for consistency. A user may want an interceptor to react to all responses, for whatever reason.

**Comment by Mitranim** [comment]
Additional note: the spec explicitly says that new or updated metainformation should be applied to the document's view. Meaning, the user agent _should_ react to a 204 response if warranted by context, they just shouldn't parse the response returned by the server, and the browsers handle this for us. All in all, I think it's fine as-is.

**Comment by SLonoed** [comment]
@Mitranim, ok, concrete example: https://github.com/strongloop/loopback/issues/621 

this refer to http://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.1

`Entity-header fields define metainformation about the entity-body or, if no body is present, about the resource identified by the request.`

xhttp try to parse 204 with contentType=application/json as json... and I have failed response.

**Comment by Mitranim** [comment]
Yeah you're right. I added a special case to response handling to skip parsing entirely when the status is 204. Response interceptors are still called, but with a `null` body value, and their return values are ignored. Please try 0.0.5 and see if this fixes your problem. I'm not merging the pull request because the proposed change would prevent interceptors from being called on an 204 request, and that might be undesirable.

**Pull request closed without merging**
